const assert = require("node:assert/strict");
const fs = require("node:fs");

const main = fs.readFileSync("static/js/main.js", "utf8");
const index = fs.readFileSync("static/index.html", "utf8");
const admin = fs.readFileSync("static/admin.html", "utf8");
const apply = fs.readFileSync("static/apply_presale.html", "utf8");
const repl = fs.readFileSync(".replit", "utf8");

assert.match(index, /data-datalab-key="presale"/);
assert.match(index, />분양중</);
assert.match(index, /미준공\(분양중\)/);
assert.match(main, /\/apply\/presale\?building=/);
assert.match(main, /lodging_type: "준공전"/);
assert.match(main, /className = "presale-building-marker"/);
assert.match(main, /<strong>분양중<\/strong><span>/);
assert.match(main, /P 분양중 현황/);
assert.match(main, /<th>지역<\/th><th>분양건물<\/th><th>비중<\/th>/);
assert.match(main, /<tfoot><tr><th>합계<\/th>/);
assert.match(main, /count \/ total \* 1000/);
assert.doesNotMatch(main, /presale-region-item/);
assert.doesNotMatch(main, /분양 후보 건물/);
const zoomBody = main.match(/async function updateMapForZoom[\s\S]*?\n}/)?.[0] || "";
assert.doesNotMatch(zoomBody, /clearPresaleOverlays/);
assert.match(main, /eligible !== true/);
assert.match(main, /u\.protocol === "https:"/);
assert.match(main, /u\.origin === location\.origin/);
assert.match(main, /applyhome_verified === true/);
assert.match(main, /청약홈 분양공고 확인/);
assert.match(admin, /verified:"확인",unverified:"미확인",not_applicable:"비대상",error:"오류"/);
assert.match(admin, /청약홈 미확인·오류여도 승인할 수 있습니다/);
assert.match(admin, /name="project_status"/);
assert.match(admin, /name="project_type"/);
assert.match(admin, /value="sold_out"/);
assert.doesNotMatch(admin, /value="scheduled">예약 공개/);
assert.match(admin, /name="remaining_units"/);
assert.match(admin, /name="move_in_date"/);
assert.match(admin, /name="editorial_body"/);
assert.match(admin, /name="contact_phone"/);
assert.match(admin, /name="company_name"/);
assert.match(admin, /name="priority"/);
assert.match(admin, /fd\.append\("file",file\)/);
assert.match(admin, /\/api\/admin\/presale\/promotions/);
assert.match(admin, /method:editPromotionId\?"PUT":"POST"/);
assert.match(admin, /method:"DELETE"/);
assert.match(admin, /optionalNumber/);
assert.match(admin, /setForm\(document\.getElementById\("presaleForm"\),p\)/);
assert.match(apply, /id="presaleApplicationForm"/);
assert.match(apply, /name="privacy_consent"/);
assert.match(apply, /name="evidence"/);
assert.match(apply, /name="applicant_role"/);
assert.doesNotMatch(apply, /name="unit_count"/);
assert.doesNotMatch(apply, /name="price_min"/);
assert.match(main, /project\?\.homepage_url\|\|"\/mypage"/);
assert.match(apply, /\/api\/presale\/applications/);
assert.match(admin, /\/api\/admin\/presale\/applications/);
assert.match(admin, /data-app-approve/);
assert.match(admin, /data-app-reject/);
assert.match(admin, /data-app-notify/);
assert.match(repl, /build\s*=\s*\["npm",\s*"run",\s*"build:frontend"\]/);

console.log("presale frontend contract: ok");
