const fs = require("fs");
const html = fs.readFileSync("static/admin.html", "utf8");
for (const text of [
  "관광 데이터랩 갱신",
  "/api/admin/tourism-datalab/preview",
  "/api/admin/tourism-datalab/apply",
  "datalab.visitkorea.or.kr",
  "tourismDatalabApply",
  "현재 조회·적용 대상:",
  "상세주소 CSV는 1~100위와 도로명주소 100개",
  "운영 DB 반영 예정",
  "관광 데이터랩 원본",
  "현재 목록: 운영 DB 원본 이력 · 적용 대상: 실제 홈페이지",
  "현재 목록: 개발 DB 참고용 · 원본 업데이트 불가",
  "운영 DB·실제 홈페이지에 적용",
  "개발에서는 업데이트하지 않음",
  "19개 관광데이터 원본은 이 운영 관리자 한 곳에서만 추가·업데이트합니다",
  "개발 관리자에는 파일을 넣지 않습니다",
  "/api/admin/tourism-datalab/collections",
  "모든 수집처",
  "업데이트 예정일",
  "운영 DB와 실제 홈페이지",
  "apply.disabled",
  "response status",
  "response.ok",
  "response.status === 401",
  "<table class=\"dg-table\"",
  "적용 자료 기준연도",
  "다음 수집 예정연도",
  "수집 출처",
  "annualTourismRosterReferenceYear",
  "annualTourismRosterNextCollectionYear",
  "annualTourismRosterSourceName",
  'body.append("reference_year", referenceYear.value)',
  'body.append("next_collection_year", nextCollectionYear.value)',
  'body.append("source_name", sourceName.value.trim())',
  "d.next_collection_year",
  "충돌·미연결은 건물에 연결하지 않습니다",
  "파일 검사·저장·홈페이지 적용",
  "저장·홈페이지 적용 완료",
  "저장·홈페이지 적용 실패",
]) {
  if (!html.includes(text)) throw new Error(`missing Data Lab admin UI: ${text}`);
}
console.log("tourism Data Lab admin UI contract passed");