// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/analysis-photo/CurrentReport.tsx": () => import("../components/mockups/analysis-photo/CurrentReport.tsx"),
  "./components/mockups/analysis-photo/DesktopWithPhoto.tsx": () => import("../components/mockups/analysis-photo/DesktopWithPhoto.tsx"),
  "./components/mockups/analysis-photo/PrintWithPhoto.tsx": () => import("../components/mockups/analysis-photo/PrintWithPhoto.tsx"),
  "./components/mockups/weekly-email/Current.tsx": () => import("../components/mockups/weekly-email/Current.tsx"),
  "./components/mockups/weekly-email/Proposal.tsx": () => import("../components/mockups/weekly-email/Proposal.tsx")
};
